<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.authentication_success_handler' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-http\\Authentication\\AuthenticationSuccessHandlerInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\Authentication\\AuthenticationSuccessHandler.php';

return $this->privates['contao.security.authentication_success_handler'] = new \Contao\CoreBundle\Security\Authentication\AuthenticationSuccessHandler(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['contao.security.two_factor.trusted_device_manager'] ?? $this->load('getContao_Security_TwoFactor_TrustedDeviceManagerService.php')), ($this->services['security.firewall.map'] ?? $this->getSecurity_Firewall_MapService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
